services:
  postgres:
    image: postgres:16-alpine
    container_name: codevault-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codevault
    ports:
      - "5433:5432"
    volumes:
      - codevault_postgres_data:/var/lib/postgresql/data
      - ./docker/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

volumes:
  codevault_postgres_data:
